url: https://githome.io
baseurl: "/jbook" # It's the default

name: JBook
name_en: JBook
title: JBook
keywords: "jekyll, book, jekyll theme"
description: "jekyll-book-theme"

markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false # syntax highlighter 和 highlight.js 不应该同时引用
  toc_levels: 2..3

# Building settings
permalink: pretty

include: ["_assets", ".images"]

exclude:
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - vendor

plugins:
  - jekyll-readme-index
  - jekyll-relative-links
  # - jekyll-sitemap
  # - jekyll-redirect-from

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: book
      toc_min: 2
      toc_max: 3
      tree: true
      permalink: /:path/:basename:output_ext

sass:
  sass_dir: _scss
  style: :compressed

# readme_index:
#   enabled: true
#   remove_originals: true
#   with_frontmatter: true

#============================= more settings =============================#

repourl: https://github.com/jinsyin/jbook
copyright: Powered by Jinsyin

# Site Language
lang: "zh-cmn-Hans" # "zh-cmn-Hans" => 简体中文; "zh-cmn-Hant" => 繁体中文; "en" => English

author:
  name: Jinsyin
  github: https://github.com/jinsyin
